# Generated by Django 4.1.3 on 2022-11-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_especialidad_delete_cita_delete_paciente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especialidad',
            new_name='Especialidade',
        ),
        migrations.RenameField(
            model_name='especialidade',
            old_name='Especialiada',
            new_name='TipoEspecialidad',
        ),
    ]
